# This file sets the basic flags for the SAC compiler
IF (NOT CMAKE_SAC_COMPILE_OBJECT)
    SET (CMAKE_SAC_COMPILE_OBJECT "<CMAKE_SAC_COMPILER> <DEFINES> <INCLUDES> -o <OBJECT> -c <SOURCE>")
ENDIF ()
IF (NOT CMAKE_SAC_CREATE_SHARED_LIBRARY)
    SET (CMAKE_C_CREATE_SHARED_LIBRARY
        "<CMAKE_SAC_COMPILER> <SONAME_FLAG><TARGET_SONAME> -o <TARGET> <OBJECTS> <LINK_LIBRARIES>")
ENDIF ()
IF (NOT CMAKE_SAC_LINK_EXECUTABLE)
    SET (CMAKE_C_LINK_EXECUTABLE
        "<CMAKE_SAC_COMPILER> <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> \
          <OBJECTS>  -o <TARGET> <LINK_LIBRARIES>")
ENDIF ()
SET (CMAKE_SAC_INFORMATION_LOADED 1)
